import { PrismaClient } from "@prisma/client";
import crypto from "crypto";

const prisma = new PrismaClient();

function getKey(): Buffer {
  const hex = process.env.ENCRYPTION_KEY;
  if (!hex || hex.length !== 64) throw new Error("ENCRYPTION_KEY not set or invalid");
  return Buffer.from(hex, "hex");
}

function encrypt(text: string): string {
  const key = getKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const encrypted = Buffer.concat([cipher.update(text, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString("hex")}:${authTag.toString("hex")}:${encrypted.toString("hex")}`;
}

function hmac(text: string): string {
  return crypto.createHmac("sha256", getKey()).update(text).digest("hex");
}

function encryptCar<T extends { vinNumber: string; registrationNumber: string }>(car: T) {
  return {
    ...car,
    vinNumber: encrypt(car.vinNumber),
    registrationNumber: encrypt(car.registrationNumber),
    vinNumberHash: hmac(car.vinNumber),
  };
}

async function main() {
  // CarPhoto has onDelete: Cascade so deleting cars cascades to photos.
  await prisma.car.deleteMany();

  const cars = [
    // ── Available ──────────────────────────────────────────────────────────
    {
      brand: "BMW",
      model: "5 Series",
      year: 2022,
      mileage: 32000,
      color: "Black",
      vinNumber: "WBA5A5C50FD520099",
      registrationNumber: "AA1234BB",
      countryOfRegistration: "Germany",
      engineType: "diesel" as const,
      engineVolume: 3.0,
      enginePower: 286,
      gearboxType: "automatic" as const,
      drivetrain: "rwd" as const,
      bodyType: "sedan" as const,
      doorsCount: 4,
      seatsCount: 5,
      carOrigin: "EU" as const,
      carLocation: "dealership" as const,
      location: "Kyiv, Showroom A",
      sellType: "retail" as const,
      isCryptoAvailable: false,
      ownerPrice: 42000,
      dealerPrice: 43500,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Бездоганний BMW 5 Series з повним пакетом опцій та сервісною книгою.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
      priceChangedAt: new Date("2026-02-14"),
    },
    {
      brand: "Mercedes-Benz",
      model: "GLE 350",
      year: 2021,
      mileage: 51000,
      color: "White",
      vinNumber: "4JGDA5HB1MA456123",
      registrationNumber: "CE5678DE",
      countryOfRegistration: "USA",
      engineType: "gasoline" as const,
      engineVolume: 3.5,
      enginePower: 333,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "suv" as const,
      doorsCount: 5,
      seatsCount: 7,
      carOrigin: "US" as const,
      carLocation: "dealership" as const,
      location: "Kyiv, Showroom A",
      sellType: "retail" as const,
      isCryptoAvailable: true,
      ownerPrice: 58000,
      dealerPrice: 60000,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Просторий 7-місний позашляховик з панорамним дахом. Розмитнений.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
    {
      brand: "Toyota",
      model: "Camry",
      year: 2023,
      mileage: 12000,
      color: "Silver",
      vinNumber: "4T1BF1FK5EU123456",
      registrationNumber: "GH9101IJ",
      countryOfRegistration: "Japan",
      engineType: "hybrid_gasoline" as const,
      engineVolume: 2.5,
      enginePower: 218,
      gearboxType: "cvt" as const,
      drivetrain: "fwd" as const,
      bodyType: "sedan" as const,
      doorsCount: 4,
      seatsCount: 5,
      carOrigin: "japan" as const,
      carLocation: "owner" as const,
      location: "Lviv, owner address",
      sellType: "consignment" as const,
      isCryptoAvailable: false,
      ownerPrice: 31000,
      dealerPrice: 32500,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Майже новий гібрид із мінімальним пробігом від першого власника.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "sales@cardealercrm.com",
    },
    {
      brand: "Audi",
      model: "Q7",
      year: 2020,
      mileage: 74000,
      color: "Dark Blue",
      vinNumber: "WA1LAAF79LD123789",
      registrationNumber: "KL1213MN",
      countryOfRegistration: "Germany",
      engineType: "diesel" as const,
      engineVolume: 3.0,
      enginePower: 249,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "suv" as const,
      doorsCount: 5,
      seatsCount: 7,
      carOrigin: "EU" as const,
      carLocation: "dealership" as const,
      location: "Odessa, Showroom B",
      sellType: "retail" as const,
      isCryptoAvailable: false,
      ownerPrice: 49000,
      dealerPrice: 50500,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Флагманський позашляховик з дизельним двигуном і 7 місцями.",
      accidentFree: false,
      crashed: true,
      airbagReplaced: false,
      crashDetails: "Незначне пошкодження переднього бампера; відновлений у сертифікованому сервісі.",
      crashBodyParts: ["front_bumper"],
      responsiblePerson: "manager@cardealercrm.com",
    },
    {
      brand: "Tesla",
      model: "Model 3",
      year: 2023,
      mileage: 8000,
      color: "Red",
      vinNumber: "5YJ3E1EA7PF123456",
      registrationNumber: "OP1415QR",
      countryOfRegistration: "USA",
      engineType: "electric" as const,
      engineVolume: 0.0,
      enginePower: 358,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "sedan" as const,
      doorsCount: 4,
      seatsCount: 5,
      carOrigin: "US" as const,
      carLocation: "dealership" as const,
      location: "Kyiv, Showroom A",
      sellType: "retail" as const,
      isCryptoAvailable: true,
      ownerPrice: 38000,
      dealerPrice: 39500,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Електричний седан з запасом ходу 500+ км. Митне оформлення в процесі.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "sales@cardealercrm.com",
    },
    {
      brand: "Ford",
      model: "F-150",
      year: 2022,
      mileage: 28000,
      color: "Black",
      vinNumber: "1FTFW1ET5NFA12345",
      registrationNumber: "WX1819YZ",
      countryOfRegistration: "USA",
      engineType: "gasoline" as const,
      engineVolume: 5.0,
      enginePower: 400,
      gearboxType: "automatic" as const,
      drivetrain: "four_wd" as const,
      bodyType: "pickup" as const,
      doorsCount: 4,
      seatsCount: 5,
      carOrigin: "US" as const,
      carLocation: "dealership" as const,
      location: "Odessa, Showroom B",
      sellType: "retail" as const,
      isCryptoAvailable: true,
      ownerPrice: 47000,
      dealerPrice: 48500,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Повнорозмірний пікап 5.0L V8. Митне оформлення не пройдено — ціна відповідна.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
    {
      brand: "Porsche",
      model: "Cayenne",
      year: 2021,
      mileage: 39000,
      color: "White",
      vinNumber: "WP1ZZZ9YZMDA12345",
      registrationNumber: "AB2021CD",
      countryOfRegistration: "Germany",
      engineType: "hybrid_gasoline" as const,
      engineVolume: 3.0,
      enginePower: 462,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "suv" as const,
      doorsCount: 5,
      seatsCount: 5,
      carOrigin: "EU" as const,
      carLocation: "dealership" as const,
      location: "Kyiv, Showroom A",
      sellType: "retail" as const,
      isCryptoAvailable: true,
      ownerPrice: 89000,
      dealerPrice: 92000,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Porsche Cayenne E-Hybrid — спортивний характер та економічність гібрида.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
    {
      brand: "Honda",
      model: "CR-V",
      year: 2020,
      mileage: 62000,
      color: "Blue",
      vinNumber: "2HKRW2H87LH123456",
      registrationNumber: "EF2223GH",
      countryOfRegistration: "Japan",
      engineType: "gasoline" as const,
      engineVolume: 1.5,
      enginePower: 190,
      gearboxType: "cvt" as const,
      drivetrain: "awd" as const,
      bodyType: "crossover" as const,
      doorsCount: 5,
      seatsCount: 5,
      carOrigin: "japan" as const,
      carLocation: "owner" as const,
      location: "Dnipro, owner address",
      sellType: "consignment" as const,
      isCryptoAvailable: false,
      ownerPrice: 22000,
      dealerPrice: 23000,
      isAvailable: true,
      listingStatus: "available" as const,
      shortDescription: "Надійний кросовер Honda у відмінному стані від власника.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "sales@cardealercrm.com",
    },
    // ── Sold ───────────────────────────────────────────────────────────────
    {
      brand: "Volkswagen",
      model: "Golf",
      year: 2019,
      mileage: 95000,
      color: "Grey",
      vinNumber: "WVWZZZ1KZAW123456",
      registrationNumber: "ST1617UV",
      countryOfRegistration: "Poland",
      engineType: "gasoline" as const,
      engineVolume: 1.4,
      enginePower: 125,
      gearboxType: "robot" as const,
      drivetrain: "fwd" as const,
      bodyType: "hatchback" as const,
      doorsCount: 5,
      seatsCount: 5,
      carOrigin: "EU" as const,
      carLocation: "owner" as const,
      location: "Kharkiv, owner address",
      sellType: "retail" as const,
      isCryptoAvailable: false,
      ownerPrice: 14500,
      dealerPrice: 15000,
      isAvailable: false,
      listingStatus: "sold" as const,
      soldAt: new Date("2026-03-10"),
      shortDescription: "Проданий Golf GTI — використовується як приклад у нещодавно проданих.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "sales@cardealercrm.com",
    },
    {
      brand: "Kia",
      model: "Stinger",
      year: 2021,
      mileage: 44000,
      color: "Orange",
      vinNumber: "KNAE35LC1M6123456",
      registrationNumber: "IJ2425KL",
      countryOfRegistration: "South Korea",
      engineType: "gasoline" as const,
      engineVolume: 3.3,
      enginePower: 370,
      gearboxType: "automatic" as const,
      drivetrain: "rwd" as const,
      bodyType: "liftback" as const,
      doorsCount: 4,
      seatsCount: 5,
      carOrigin: "korea" as const,
      carLocation: "dealership" as const,
      location: "Kyiv, Showroom A",
      sellType: "retail" as const,
      isCryptoAvailable: false,
      ownerPrice: 33000,
      dealerPrice: 34500,
      isAvailable: false,
      listingStatus: "sold" as const,
      soldAt: new Date("2026-04-01"),
      shortDescription: "Kia Stinger GT — потужний ліфтбек. Продано.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
    // ── Upcoming ───────────────────────────────────────────────────────────
    {
      brand: "Lexus",
      model: "RX 500h",
      year: 2024,
      mileage: 0,
      color: "Sonic Chrome",
      vinNumber: "JTJBAMCA1R2123456",
      registrationNumber: "NEW2024LX",
      countryOfRegistration: "Japan",
      engineType: "hybrid_gasoline" as const,
      engineVolume: 2.4,
      enginePower: 371,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "suv" as const,
      doorsCount: 5,
      seatsCount: 5,
      carOrigin: "japan" as const,
      carLocation: "dealership" as const,
      location: "В дорозі",
      sellType: "retail" as const,
      isCryptoAvailable: false,
      ownerPrice: 72000,
      dealerPrice: 74000,
      estimatedPrice: 79000,
      isAvailable: false,
      listingStatus: "upcoming" as const,
      eta: new Date("2026-06-15"),
      transitStage: "in_transit" as const,
      shortDescription: "Новий Lexus RX 500h F Sport — очікується у червні 2026.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
    {
      brand: "BMW",
      model: "iX xDrive50",
      year: 2024,
      mileage: 0,
      color: "Mineral White",
      vinNumber: "WBY8P210X0RC12345",
      registrationNumber: "NEW2024IX",
      countryOfRegistration: "Germany",
      engineType: "electric" as const,
      engineVolume: 0.0,
      enginePower: 523,
      gearboxType: "automatic" as const,
      drivetrain: "awd" as const,
      bodyType: "suv" as const,
      doorsCount: 5,
      seatsCount: 5,
      carOrigin: "EU" as const,
      carLocation: "dealership" as const,
      location: "В дорозі",
      sellType: "retail" as const,
      isCryptoAvailable: true,
      ownerPrice: 95000,
      dealerPrice: 98000,
      estimatedPrice: 104000,
      isAvailable: false,
      listingStatus: "upcoming" as const,
      eta: new Date("2026-07-01"),
      transitStage: "at_port" as const,
      shortDescription: "Флагманський електричний BMW iX — у порту, очікує розмитнення.",
      accidentFree: true,
      crashed: false,
      airbagReplaced: false,
      crashBodyParts: [],
      responsiblePerson: "manager@cardealercrm.com",
    },
  ];

  await prisma.car.createMany({ data: cars.map(encryptCar) });

  console.log(`Seeded ${cars.length} cars (${cars.filter(c => c.listingStatus === "available").length} available, ${cars.filter(c => c.listingStatus === "sold").length} sold, ${cars.filter(c => c.listingStatus === "upcoming").length} upcoming).`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
