import { PrismaClient } from "@prisma/client";
import crypto from "crypto";

const prisma = new PrismaClient();

function getKey(): Buffer {
  const hex = process.env.ENCRYPTION_KEY;
  if (!hex || hex.length !== 64) throw new Error("ENCRYPTION_KEY not set or invalid");
  return Buffer.from(hex, "hex");
}

function encrypt(text: string): string {
  const key = getKey();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv("aes-256-gcm", key, iv);
  const encrypted = Buffer.concat([cipher.update(text, "utf8"), cipher.final()]);
  const authTag = cipher.getAuthTag();
  return `${iv.toString("hex")}:${authTag.toString("hex")}:${encrypted.toString("hex")}`;
}

function hmac(text: string): string {
  return crypto.createHmac("sha256", getKey()).update(text).digest("hex");
}

function encryptCar<T extends { vinNumber: string; registrationNumber: string }>(car: T) {
  return {
    ...car,
    vinNumber: encrypt(car.vinNumber),
    registrationNumber: encrypt(car.registrationNumber),
    vinNumberHash: hmac(car.vinNumber),
  };
}

async function main() {
  await prisma.car.deleteMany();

  await prisma.car.createMany({
    data: [
      {
        brand: "BMW",
        model: "5 Series",
        year: 2022,
        mileage: 32000,
        color: "Black",
        vinNumber: "WBA5A5C50FD520099",
        registrationNumber: "AA1234BB",
        countryOfRegistration: "Germany",
        engineType: "diesel",
        engineVolume: 3.0,
        enginePower: 286,
        gearboxType: "automatic",
        drivetrain: "rwd",
        bodyType: "sedan",
        doorsCount: 4,
        seatsCount: 5,
        cabinType: "standard",
        customsStatus: "cleared",
        carOrigin: "EU",
        carLocation: "dealership",
        location: "Kyiv, Showroom A",
        sellType: "retail",
        isCryptoAvailable: false,
        ownerPrice: 42000,
        websitePrice: 45900,
        dealerPrice: 43500,
        generalPrice: 43000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
        priceChangedAt: new Date("2026-02-14"),
      },
      {
        brand: "Mercedes-Benz",
        model: "GLE 350",
        year: 2021,
        mileage: 51000,
        color: "White",
        vinNumber: "4JGDA5HB1MA456123",
        registrationNumber: "CE5678DE",
        countryOfRegistration: "USA",
        engineType: "gasoline",
        engineVolume: 3.5,
        enginePower: 333,
        gearboxType: "automatic",
        drivetrain: "awd",
        bodyType: "suv",
        doorsCount: 5,
        seatsCount: 7,
        cabinType: "panoramic",
        customsStatus: "cleared",
        carOrigin: "US",
        carLocation: "dealership",
        location: "Kyiv, Showroom A",
        sellType: "retail",
        isCryptoAvailable: true,
        ownerPrice: 58000,
        websitePrice: 63500,
        dealerPrice: 60000,
        generalPrice: 59000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
      },
      {
        brand: "Toyota",
        model: "Camry",
        year: 2023,
        mileage: 12000,
        color: "Silver",
        vinNumber: "4T1BF1FK5EU123456",
        registrationNumber: "GH9101IJ",
        countryOfRegistration: "Japan",
        engineType: "hybrid_gasoline",
        engineVolume: 2.5,
        enginePower: 218,
        gearboxType: "cvt",
        drivetrain: "fwd",
        bodyType: "sedan",
        doorsCount: 4,
        seatsCount: 5,
        cabinType: "standard",
        customsStatus: "cleared",
        carOrigin: "japan",
        carLocation: "owner",
        location: "Lviv, owner address",
        sellType: "consignment",
        isCryptoAvailable: false,
        ownerPrice: 31000,
        websitePrice: 34500,
        dealerPrice: 32500,
        generalPrice: 32000,
        isAvailable: true,
        responsiblePerson: "sales@cardealercrm.com",
      },
      {
        brand: "Audi",
        model: "Q7",
        year: 2020,
        mileage: 74000,
        color: "Dark Blue",
        vinNumber: "WA1LAAF79LD123789",
        registrationNumber: "KL1213MN",
        countryOfRegistration: "Germany",
        engineType: "diesel",
        engineVolume: 3.0,
        enginePower: 249,
        gearboxType: "automatic",
        drivetrain: "awd",
        bodyType: "suv",
        doorsCount: 5,
        seatsCount: 7,
        cabinType: "panoramic",
        customsStatus: "cleared",
        carOrigin: "EU",
        carLocation: "dealership",
        location: "Odessa, Showroom B",
        sellType: "retail",
        isCryptoAvailable: false,
        ownerPrice: 49000,
        websitePrice: 53000,
        dealerPrice: 50500,
        generalPrice: 50000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
      },
      {
        brand: "Tesla",
        model: "Model 3",
        year: 2023,
        mileage: 8000,
        color: "Red",
        vinNumber: "5YJ3E1EA7PF123456",
        registrationNumber: "OP1415QR",
        countryOfRegistration: "USA",
        engineType: "electric",
        engineVolume: 0.0,
        enginePower: 358,
        gearboxType: "automatic",
        drivetrain: "awd",
        bodyType: "sedan",
        doorsCount: 4,
        seatsCount: 5,
        cabinType: "panoramic",
        customsStatus: "in_progress",
        carOrigin: "US",
        carLocation: "dealership",
        location: "Kyiv, Showroom A",
        sellType: "retail",
        isCryptoAvailable: true,
        ownerPrice: 38000,
        websitePrice: 42000,
        dealerPrice: 39500,
        generalPrice: 39000,
        isAvailable: true,
        responsiblePerson: "sales@cardealercrm.com",
      },
      {
        brand: "Volkswagen",
        model: "Golf",
        year: 2019,
        mileage: 95000,
        color: "Grey",
        vinNumber: "WVWZZZ1KZAW123456",
        registrationNumber: "ST1617UV",
        countryOfRegistration: "Poland",
        engineType: "gasoline",
        engineVolume: 1.4,
        enginePower: 125,
        gearboxType: "robot",
        drivetrain: "fwd",
        bodyType: "hatchback",
        doorsCount: 5,
        seatsCount: 5,
        cabinType: "standard",
        customsStatus: "cleared",
        carOrigin: "EU",
        carLocation: "owner",
        location: "Kharkiv, owner address",
        sellType: "retail",
        isCryptoAvailable: false,
        ownerPrice: 14500,
        websitePrice: 16200,
        dealerPrice: 15000,
        generalPrice: 14800,
        isAvailable: false,
        responsiblePerson: "sales@cardealercrm.com",
      },
      {
        brand: "Ford",
        model: "F-150",
        year: 2022,
        mileage: 28000,
        color: "Black",
        vinNumber: "1FTFW1ET5NFA12345",
        registrationNumber: "WX1819YZ",
        countryOfRegistration: "USA",
        engineType: "gasoline",
        engineVolume: 5.0,
        enginePower: 400,
        gearboxType: "automatic",
        drivetrain: "four_wd",
        bodyType: "pickup",
        doorsCount: 4,
        seatsCount: 5,
        cabinType: "crew_cab",
        customsStatus: "not_cleared",
        carOrigin: "US",
        carLocation: "dealership",
        location: "Odessa, Showroom B",
        sellType: "retail",
        isCryptoAvailable: true,
        ownerPrice: 47000,
        websitePrice: 51500,
        dealerPrice: 48500,
        generalPrice: 48000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
      },
      {
        brand: "Porsche",
        model: "Cayenne",
        year: 2021,
        mileage: 39000,
        color: "White",
        vinNumber: "WP1ZZZ9YZMDA12345",
        registrationNumber: "AB2021CD",
        countryOfRegistration: "Germany",
        engineType: "hybrid_gasoline",
        engineVolume: 3.0,
        enginePower: 462,
        gearboxType: "automatic",
        drivetrain: "awd",
        bodyType: "suv",
        doorsCount: 5,
        seatsCount: 5,
        cabinType: "panoramic",
        customsStatus: "cleared",
        carOrigin: "EU",
        carLocation: "dealership",
        location: "Kyiv, Showroom A",
        sellType: "retail",
        isCryptoAvailable: true,
        ownerPrice: 89000,
        websitePrice: 97000,
        dealerPrice: 92000,
        generalPrice: 91000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
      },
      {
        brand: "Honda",
        model: "CR-V",
        year: 2020,
        mileage: 62000,
        color: "Blue",
        vinNumber: "2HKRW2H87LH123456",
        registrationNumber: "EF2223GH",
        countryOfRegistration: "Japan",
        engineType: "gasoline",
        engineVolume: 1.5,
        enginePower: 190,
        gearboxType: "cvt",
        drivetrain: "awd",
        bodyType: "crossover",
        doorsCount: 5,
        seatsCount: 5,
        cabinType: "standard",
        customsStatus: "cleared",
        carOrigin: "japan",
        carLocation: "owner",
        location: "Dnipro, owner address",
        sellType: "consignment",
        isCryptoAvailable: false,
        ownerPrice: 22000,
        websitePrice: 24500,
        dealerPrice: 23000,
        generalPrice: 22800,
        isAvailable: true,
        responsiblePerson: "sales@cardealercrm.com",
      },
      {
        brand: "Kia",
        model: "Stinger",
        year: 2021,
        mileage: 44000,
        color: "Orange",
        vinNumber: "KNAE35LC1M6123456",
        registrationNumber: "IJ2425KL",
        countryOfRegistration: "South Korea",
        engineType: "gasoline",
        engineVolume: 3.3,
        enginePower: 370,
        gearboxType: "automatic",
        drivetrain: "rwd",
        bodyType: "liftback",
        doorsCount: 4,
        seatsCount: 5,
        cabinType: "standard",
        customsStatus: "cleared",
        carOrigin: "korea",
        carLocation: "dealership",
        location: "Kyiv, Showroom A",
        sellType: "retail",
        isCryptoAvailable: false,
        ownerPrice: 33000,
        websitePrice: 36500,
        dealerPrice: 34500,
        generalPrice: 34000,
        isAvailable: true,
        responsiblePerson: "manager@cardealercrm.com",
      },
    ].map(encryptCar),
  });

  console.log("Seeded 10 cars successfully.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
