FROM node:20-alpine

RUN apk add --no-cache postgresql-client openssl

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD sh -c "npx prisma migrate deploy && npm run dev"
